### ISSUE TITLE
Ping Pong example not working on OSX

### ISSUE THREAD

**Issue by tmcgilchrist** [janestreet/async_parallel#1]
I'm not really sure if async_parallel is supposed to work on OSX or if I'm doing something horribly wrong.

Below is my shell commands from trying to compile and run the ping_pong example after installing async_parallel via opam.

```
➜  ocaml  corebuild -pkg async,async_parallel ping_pong.native
➜  ocaml  ./ping_pong.native 
Uncaught exception:

  (Unix.Unix_error "No such file or directory" readlink
   "((filename /proc/4775/exe))")

Raised at file "lib/core_unix.ml", line 48, characters 11-42
Called from file "lib/master_process.ml", line 408, characters 21-83
Called from file "lib/master_process.ml", line 477, characters 10-32
Re-raised at file "lib/master_process.ml", line 483, characters 14-15
Called from file "lib/intf.ml", line 10, characters 22-53
Called from file "ping_pong.ml", line 22, characters 4-140
Called from file "lib/exn.ml", line 87, characters 6-10
```

So I tried checking out the source in github and compiling the examples there, but there's a dependency on async_kernel which doesn't appear to be available on opam.

```
➜  async_parallel git:(master) make
./setup-dev.exe -build 
W: No replace section found in file Makefile
Finished, 1 target (0 cached) in 00:00:00.
+ ocamlfind ocamlc -c -g -package threads -package sexplib.syntax -package sexplib -package core -package bin_prot.syntax -package bin_prot -package async -syntax camlp4o -thread -I lib -o lib/import.cmo lib/import.ml
File "lib/import.ml", line 10, characters 15-33:
Error: Unbound module Async_kernel
Command exited with code 2.
Compilation unsuccessful after building 3 targets (0 cached) in 00:00:01.
E: Failure("Command ''/Users/tim/.opam/4.01.0/bin/ocamlbuild' lib/async_parallel.cma lib/async_parallel.cmxa lib/async_parallel.a lib/async_parallel.cmxs examples/deep.native examples/echo_server.native examples/pingpong.native examples/ring.native examples/simple.native examples/wide.native -tag debug' terminated with error code 10")
make: *** [build] Error 1
```

I'd really like to get some working code with async_parallel. If there are some steps I'm missing or some docs I could look at please point them out.

async_parallel looks like an exciting extension to the existing async functionality and it would be fantastic to have a smooth / well documented way for people to start using it.

Thanks

**Comment by ghost** [comment]
async_kernel is available in opam: http://opam.ocaml.org/packages/async_kernel/async_kernel.111.03.00/

Maybe you need to run `opam update`?

But I'm not sure if async_parallel works on OSX. Due to the error you get it seems it doesn't, we'll have to change this for non-linux systems.

**Comment by tmcgilchrist** [comment]
My fault, I was running an old version of opam.
It compiles but doesn't run, seems like it's linux only for the moment. 

```
➜  ocaml  ./ping_pong.native 
Uncaught exception:

  (Unix.Unix_error "No such file or directory" readlink
   "((filename /proc/27875/exe))")

Raised at file "lib/core_unix.ml", line 48, characters 11-42
Called from file "lib/master_process.ml", line 415, characters 21-83
Called from file "lib/master_process.ml", line 483, characters 10-32
Re-raised at file "lib/master_process.ml", line 489, characters 14-15
Called from file "lib/intf.ml", line 10, characters 22-53
Called from file "ping_pong.ml", line 22, characters 4-140
Called from file "lib/exn.ml", line 69, characters 6-10
```

**Comment by tmcgilchrist** [comment]
So I did a little digging over the weekend and found that OSX provides a system call to get the path of an executable given the PID. When I patch that in to replace the sections that depend on the proc filesystem the programs run but I don't get any io back from the worker processes. It would seem there are a few more problems with IO under OSX.

```
(* corebuild -pkg ctypes.foreign -lflags -cclib,-lproc proc_test.native *)
open Core.Std
open Unix
open Ctypes
open Foreign

(*
  int proc_pidpath(int pid, void * buffer, uint32_t  buffersize);
*)
module Proc : sig
 val pidpath : int -> string
 (** @raise [Unix.Unix_error] in case of error *)
end = struct
  open Ctypes
  open Foreign

  let pidpathinfo_maxsize = 1024 * 4

  let char_array_as_string a len =
    let b = Buffer.create len in
    for i = 0 to len -1 do Buffer.add_char b (Array.get a i) done;
    Buffer.contents b

  let pidpath =
    foreign ~check_errno:true "proc_pidpath"
            (int @-> ptr char @-> int @-> returning int)

  let pidpath pid =
    let path = Array.make char ~initial:'\x00' pidpathinfo_maxsize in
    let len = pidpath pid (Array.start path) pidpathinfo_maxsize in
    char_array_as_string path len
end

let () =
  let pid = Unix.getpid(Proc.pidpath(Unix.to_int(Unix.getpid))) in
  printf("Pid: %i", pid)

```

**Comment by estokes** [comment]
Hi tmcgilchrist, I hadn't ever tried it on OS X, thanks for that. I'm not surprised it doesn't work. I don't anticipate that it will be that hard to make it work on OS X. Besides /proc there is probably just some tiny difference in semantics, but I'm not sure when I'll have time to investigate further.

**Comment by tmcgilchrist** [comment]
I'll do some more digging, it's fun and forcing me to learn more OCaml. Some of the examples work fine (deep.ml and echo_server.ml) the rest of them run without throwing an error but don't output anything.

**Comment by bmillwood** [comment]
Async_parallel is now deprecated in favour of Rpc_parallel, so I think it's unlikely any more work will be done to fix this (or other) issues.
