### ISSUE TITLE
Parallel.init fails quite silently

### ISSUE THREAD

**Issue by smondet** [janestreet/async_parallel#2]
I have some code with

``` ocaml
Parallel.init ~cluster ();
```

and (it happens) one of the machines in `cluster` does not accept SSH connections.

The program just terminates with code `141`, there is no exception, no error message.

**Comment by bmillwood** [comment]
Now that Async_parallel is deprecated in favour of Rpc_parallel, I think it's fairly unlikely any more bugs are going to be fixed.
